{% set name = "ubtsl" %}
{% set version = "0.0.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ubtsl-{{ version }}.tar.gz
  sha256: 9e2b39f389f3742120cab54979211f99b8980775180e01e1cd9ac371bd80a146

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - unicorn-binance-trailing-stop-loss

test:
  imports:
    - ubtsl
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://www.lucit.tech/unicorn-binance-trailing-stop-loss.html
  summary: Short module name for unicorn_binance_trailing_stop_loss 
  description: |
    Short module name for unicorn_binance_trailing_stop_loss 
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/LUCIT-Systems-and-Development/ubtsl

extra:
  recipe-maintainers:
    - oliver-zehentleitner
